name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-python:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.7

      - id: lint
        name: Lint
        run: make lint

  test-python:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    name: Test Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: ${{ matrix.python }}

      - id: run
        name: Run
        run: make test

  lint-build:
    name: Build Python package
    runs-on: ubuntu-latest
    needs: [test-python]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.7

      - id: build
        name: Build release
        run: make build-release

      - id: check
        name: Check release
        run: make check-release

      - id: save
        name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-release-${{ github.run_number }}
          path: ./dist
          if-no-files-found: error
