name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  update:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: ${{ matrix.python }}

<<<<<<< HEAD
      - id: run
        name: Run
        run: make test
=======
      - id: lint
        name: Lint
        run: pipenv run flake8 ./

      - id: test
        name: Test
        run: pipenv run python setup.py test
>>>>>>> f57bad43ad8a6b4b299f64edeb1268d961f77206
